### ISSUE TITLE
Long-term plan

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#78]
### Prototype
- [ ] Add feed
- [ ] Feed management
- [ ] Feed syncing
- [ ] Base visual language
- [ ] Fast feed
- [ ] Slow posts

### Announce
- [ ] h+h lab new website
- [ ] Mail subscription service
- [ ] Landing text
- [ ] Landing website
- [ ] Landing deploy

### Dogfooding State
- [ ] OPML import/export
- [ ] Full state import/export
- [ ] Loader integration tests for loading and looking
- [ ] Add deploy
- [ ] Add server
- [ ] Add mobile
- [ ] Log syncing improvements
- [ ] Add syncing into refreshing

### Semi-public Alpha
- [ ] Add performance tests
- [ ] Fix main performance issues
- [ ] Contributions docs
- [ ] Add welcome page
- [ ] Add feed not-found guide
- [ ] Clean old fast posts
- [ ] Add CoC
- [ ] Add discussion platform
